title: 'Ingress: Melbourne Resistance'
tagline: Play (Ingress) Melbourne
org: Melbourne Resistance
base_url: ''

profiles:
  development:
    short_name: Dev
  production:
    short_name: Home
    google_analytics:
      account: UA-40180228-3
    minify: true
    haml:
      :ugly: true
    scss:
      :style: :compressed
    deploy:
      type: s3
      bucket: s3://melb.vic.blue/

